/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ealden' at '11/18/16 12:57 AM' with Gradle 3.2
 *
 * @author ealden, @date 11/18/16 12:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
